<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Title is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Title is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Title is not matching:actiTIME - Enter Time- Track]]>
    </line>
    <line>
      <![CDATA[Title is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[element is matching : Username or Password is invalid. Please try again.]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="61929" started-at="2017-11-15T12:01:57Z" finished-at="2017-11-15T12:02:59Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="61929" started-at="2017-11-15T12:01:57Z" finished-at="2017-11-15T12:02:59Z">
      <class name="com.actitime.test.VerifyVersionTest">
        <test-method status="PASS" signature="preconditions()[pri:0, instance:com.actitime.test.VerifyVersionTest@7823a2f9]" name="preconditions" is-config="true" duration-ms="16424" started-at="2017-11-15T17:31:57Z" finished-at="2017-11-15T17:32:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preconditions -->
        <test-method status="FAIL" signature="testVersion()[pri:0, instance:com.actitime.test.VerifyVersionTest@7823a2f9]" name="testVersion" duration-ms="1086" started-at="2017-11-15T17:32:13Z" finished-at="2017-11-15T17:32:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [actiTIME 2017.4] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [actiTIME 2017.4] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.actitime.page.LoginPage.verifyVersion(LoginPage.java:62)
	at com.actitime.test.VerifyVersionTest.testVersion(VerifyVersionTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Title is matching :actiTIME - Login]]>
            </line>
          </reporter-output>
        </test-method> <!-- testVersion -->
        <test-method status="PASS" signature="postConditions()[pri:0, instance:com.actitime.test.VerifyVersionTest@7823a2f9]" name="postConditions" is-config="true" duration-ms="2234" started-at="2017-11-15T17:32:15Z" finished-at="2017-11-15T17:32:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postConditions -->
      </class> <!-- com.actitime.test.VerifyVersionTest -->
      <class name="com.actitime.test.ValidLoginTest">
        <test-method status="PASS" signature="preconditions()[pri:0, instance:com.actitime.test.ValidLoginTest@4cc0edeb]" name="preconditions" is-config="true" duration-ms="11922" started-at="2017-11-15T17:32:17Z" finished-at="2017-11-15T17:32:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preconditions -->
        <test-method status="FAIL" signature="testValidLogin()[pri:0, instance:com.actitime.test.ValidLoginTest@4cc0edeb]" name="testValidLogin" duration-ms="10641" started-at="2017-11-15T17:32:29Z" finished-at="2017-11-15T17:32:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.actitime.generic.BasePage.verifyTitle(BasePage.java:33)
	at com.actitime.page.LoginPage.verifyingTitle(LoginPage.java:57)
	at com.actitime.test.ValidLoginTest.testValidLogin(ValidLoginTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Title is matching :actiTIME - Login]]>
            </line>
            <line>
              <![CDATA[Title is not matching:actiTIME - Enter Time- Track]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method status="PASS" signature="postConditions()[pri:0, instance:com.actitime.test.ValidLoginTest@4cc0edeb]" name="postConditions" is-config="true" duration-ms="2338" started-at="2017-11-15T17:32:40Z" finished-at="2017-11-15T17:32:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postConditions -->
      </class> <!-- com.actitime.test.ValidLoginTest -->
      <class name="com.actitime.test.InValidLoginTest">
        <test-method status="PASS" signature="preconditions()[pri:0, instance:com.actitime.test.InValidLoginTest@457e2f02]" name="preconditions" is-config="true" duration-ms="11438" started-at="2017-11-15T17:32:42Z" finished-at="2017-11-15T17:32:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preconditions -->
        <test-method status="PASS" signature="testInvalidLogin()[pri:0, instance:com.actitime.test.InValidLoginTest@457e2f02]" name="testInvalidLogin" duration-ms="2834" started-at="2017-11-15T17:32:54Z" finished-at="2017-11-15T17:32:57Z">
          <reporter-output>
            <line>
              <![CDATA[Title is matching :actiTIME - Login]]>
            </line>
            <line>
              <![CDATA[element is matching : Username or Password is invalid. Please try again.]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="postConditions()[pri:0, instance:com.actitime.test.InValidLoginTest@457e2f02]" name="postConditions" is-config="true" duration-ms="2330" started-at="2017-11-15T17:32:57Z" finished-at="2017-11-15T17:32:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postConditions -->
      </class> <!-- com.actitime.test.InValidLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
